### ISSUE TITLE
Try Adding Javascript

### ISSUE THREAD

**Issue by amish1211** [ramanabhinav7/OnlineCalculator#2]
Adding a javascript file for the logic implementation of the calculator is a good idea

**Comment by ramanabhinav7** [comment]
yes, sir you are right! i will update it in some time.

**Comment by ramanabhinav7** [comment]
sir update according to your wish, and i am waiting for you pr .

**Comment by Madeye251002** [comment]
hi i would like to work on this issue. is anyone assigned?

**Comment by ramanabhinav7** [comment]
you may work now by taking branchh from main

**Comment by ramanabhinav7** [comment]
Approved ! am closing this for now
