### ISSUE TITLE
please fix the input bar, as the it is a little big!

### ISSUE THREAD

**Issue by ramanabhinav7** [ramanabhinav7/OnlineCalculator#5]
@Madeye251002  please fix the input bar!
![image](https://github.com/user-attachments/assets/17d1238e-30f9-4e9f-ac6b-d91baa65809d)

**Comment by shaalan-ahmed** [comment]
working on it

**Comment by shaalan-ahmed** [comment]
i created a pull request with the changes

**Comment by ramanabhinav7** [comment]
Approved ! am closing this for now
